config/routes.rb
Rails.application.routes.draw do
  root to: "plants#index"

  resources :plants do
    member do
      get :graph
    end
  end

  namespace :api do
    namespace :v1 do
      resources :plants, path: "devices" do
        resources :measurements
      end
    end
  end
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  scope :newest_first, ->{ order("created_at DESC") }
  scope :latest, ->{ newest_first.first }
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  has_many :measurements, dependent: :destroy

  def moisture_points
    1 - measurements.latest.moisture
  end
end

app/controllers/api/v1/measurements_controller.rb
class Api::V1::MeasurementsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @plant = Plant.where(identifier: params[:plant_id]).first_or_create
    @measurement = @plant.measurements.create(moisture: params[:moisture])

    render nothing: true
  end
end

app/controllers/api/v1/plants_controller.rb
class Api::V1::PlantsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy, :graph]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  def graph
    render json: @plant.measurements.group_by_day(:created_at, last: 7).average(:moisture)
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
    @measurements = @plant.measurements.newest_first
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params[:plant]
    end
end

app/helpers/api/v1/measurements_helper.rb
module Api::V1::MeasurementsHelper
end

app/helpers/api/v1/plants_helper.rb
module Api::V1::PlantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plantwise</title>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="PlantWise">
</head>
<body class="fixed-navbar">

<%= yield %>

</body>
</html>

app/views/measurements/_measurement.html.erb
<tr>
  <td><%= measurement.moisture %></td><td><%= measurement.created_at %></td>
</tr>

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plants/_index.html.erb
<div id="plants-page" class="view-page" data-role="page">
  <div class="container-fluid">

    <%= render @plants %>

  </div>

</div>

app/views/plants/_navbar.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-4">
      <%= link_to :back, remote: true, class: "navbar-back" do %>
        <%= icon("angle-left", "Back", class: "fa-lg") %>
      <% end %>
    </div>
    <div class="col-xs-4 text-center">
      <div class="navbar-title"><%= @plant.identifier.humanize %></div>
    </div>
    <div class="col-xs-4">
    </div>
  </div>
</div>

app/views/plants/_navbar_index.html.erb
<div class="container-fluid">
  <div class="col-xs-3">
  </div>
  <div class="col-xs-6 text-center">
    <div class="navbar-title">Plants</div>
  </div>
  <div class="col-xs-3">
  </div>
</div>

app/views/plants/_plant.html.erb
<%= content_tag_for(:a, plant, href: plant_path(plant), class: "row", data: { remote: true } ) do %>
  <div class="col-xs-8">
    <h3><%= plant.identifier.humanize %></h3>
  </div>
  <div class="col-xs-4 text-center">
    <div data-behavior="circle-progress" data-circle-value="<%= plant.moisture_points %>" data-circle-color="#5bc0de" class="plant-health-circle">
    </div>
  </div>
<% end %>

app/views/plants/_show.html.erb
<div id="plant-page" class="view-page" data-role="page">

  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <%= line_chart graph_plant_path(@plant), min: 0, max: 1, discrete: true %>

      </div>
    </div>
  </div>

</div>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<div class="ios-top-statusbar-background">
</div>

<nav class="navbar navbar-default navbar-fixed-top navbar-visible navbar-custom" id="navbar-fixed">
  <%= render "navbar_index" %>
</nav>

<%= render "index" %>

<script type="text/javascript">
  $(document).ready(function() {
    FastClick.attach(document.body);


      $("[data-behavior=circle-progress]").each(function() {
        var circle_value = $(this).data("circle-value");
        var circle_color = $(this).data("circle-color");
        $(this).circleProgress({
          value: circle_value,
          size: 100,
          startAngle: -Math.PI / 2,
          animationStartValue: 1.0,
          fill: {
            color: circle_color
          }
        })
      })


    if(navigator.standalone) {
      $("body").addClass("standalone");
    }

    var touchStart = 0;

    $("body").on("touchstart", function(event) {
      touchStart = $(this).scrollTop();
    })

    $("body").on("touchmove", function(event) {
      var newScrollTop = $(this).scrollTop()

      if (newScrollTop >= touchStart && newScrollTop > 80) {
        $("#navbar-fixed").switchClass("navbar-visible", "navbar-invisible")
      } else if (newScrollTop < touchStart){
        $("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
      }
    })

    $(window).scroll(function() {
      var newScrollTop = $(this).scrollTop()

      if (newScrollTop <= 0) {
        $("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
      } else if (newScrollTop >= touchStart && newScrollTop > 80) {
        $("#navbar-fixed").switchClass("navbar-visible", "navbar-invisible")
      } else if (newScrollTop < touchStart){
        $("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
      }
    })

    $("body").on("touchend", function(event) {
      var newScrollTop = $(this).scrollTop()

      if (newScrollTop <= 0) {
        $("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
      } else if (newScrollTop >= touchStart && newScrollTop > 80) {
        $("#navbar-fixed").switchClass("navbar-visible", "navbar-invisible")
      } else if (newScrollTop < touchStart){
        $("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
      }
    })

    $("<style>").prop("type", "text/css").html("\
\
    @-webkit-keyframes slide-left {\
      from { -webkit-transform: translateX(" + $(window).width() + "px); opacity: 0; }\
      to { -webkit-transform: translateX(0px); opacity: 1; }\
    }\
\
    @-webkit-keyframes slide-right {\
      from { -webkit-transform: translateX(" + (-$(window).width()) + "px); opacity: 0;}\
      to { -webkit-transform: translateX(0px); opacity: 1; }\
    }\
\
    @-webkit-keyframes hide-left {\
      from { -webkit-transform: translateX(0px); opacity: 1; }\
      to { -webkit-transform: translateX(-40px); opacity: 0;}\
    }\
\
    @-webkit-keyframes hide-right {\
      from { -webkit-transform: translateX(0px); opacity: 1; }\
      to { -webkit-transform: translateX(40px); opacity: 0; }\
    }\
\
    .forward-page {\
      -webkit-transform: translateX(" + $(window).width() + "px);\
    }\
\
    .backward-page {\
      -webkit-transform: translateX(" + (-$(window).width()) + "px);\
    }\
\
    .view-page {\
      min-height: " + $(window).height() + "px; \
    }\
").appendTo("head")

  })
</script>

<% if false %>
.view-page { \
  width: " + $(window).width() + "px; \
  height: " + $(window).height() + "px; \
  overflow: auto; \
  -webkit-overflow-scrolling: touch; \
}
<% end %>

app/views/plants/index.js.erb
var new_page_html = $("<%= j render "index" %>")
new_page_html.addClass("backward-page")
var current_page = $(".view-page")
current_page.after(new_page_html)
current_page.css({"position": "absolute", width: $(window).width() })

// current_page.addClass("hide-to-right")
new_page_html.addClass("slide-right")
$("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
$("body").scrollTop(0)
setTimeout(function() {
  current_page.remove()
}, 400);

new_navbar_html = $("<%= j render "navbar_index" %>")
new_navbar_html.css({opacity: 0})
$("#navbar-fixed").html(new_navbar_html)
new_navbar_html.addClass("navbar-slide-back")

$("[data-behavior=circle-progress]").each(function() {
  var circle_value = $(this).data("circle-value");
  var circle_color = $(this).data("circle-color");
  $(this).circleProgress({
    value: circle_value,
    size: 100,
    startAngle: -Math.PI / 2,
    animationStartValue: 1.0,
    fill: {
      color: circle_color
    }
  })
})

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.js.erb
var new_page_html = $("<%= j render "show" %>")
new_page_html.addClass("forward-page")
var current_page = $(".view-page")
current_page.css({"position": "absolute", "width": $(window).width()})
current_page.after(new_page_html)

new_page_html.addClass("slide-left")
current_page.addClass("hide-to-left")
$("body").scrollTop(0)
$("#navbar-fixed").switchClass("navbar-invisible", "navbar-visible")
setTimeout(function() {
  current_page.remove()
}, 400)

new_navbar_html = $("<%= j render "navbar" %>")
new_navbar_html.css({opacity: 0})
$("#navbar-fixed").html(new_navbar_html)
new_navbar_html.addClass("navbar-slide-in")